-- ============ PHASES ============
INSERT INTO phases (sort_order, code, title, subtitle, track) VALUES
(1,'P1','Phase 1: Sun Tzu - The Art of War','Win before fighting. 13 chapters + integration exam.','strategy'),
(2,'P2','Phase 2: Machiavelli - The Prince','Cold anthropology of power. 26 chapters in 9 units + exam.','strategy'),
(3,'P2B','Phase 2B: Discourses on Livy','The mature Machiavelli almost nobody reads. Where real mastery lives.','strategy'),
(4,'P3','Phase 3: The Supporting Canon','Greene, Musashi, Clausewitz - the modern synthesis.','strategy'),
(5,'PHIL','Philosophy Track: The Mind Forge','Stoics -> Plato -> Nietzsche. Runs in your 20:15 nightly block.','philosophy');

-- ============ PHASE 1: SUN TZU (phase_id=1) ============
INSERT INTO units (phase_id, sort_order, title, reading, lesson, field_drill, debrief_prompt, is_exam, exam_questions) VALUES
(1,1,'Ch.1 - Laying Plans','Art of War, Chapter 1 (read twice: once fast, once with pen)','War is governed by five factors: Moral Law (why you fight), Heaven (timing), Earth (terrain/context), Command (leadership), Method (discipline/systems). All warfare is based on deception - but first, on CALCULATION. The general who wins makes many calculations before the battle. Victory is decided before the first move.','Tonight, before bed, run the Five Factors on ONE current battle in your life (a deadline, an exam, a goal): Why am I fighting? Is the timing right? What is the terrain? Who commands (my discipline)? What is my method? Write the answers in your drill report.','Where today did I act WITHOUT calculating first - and what did it cost me?',0,NULL),
(1,2,'Ch.2 - Waging War','Art of War, Chapter 2','Prolonged war exhausts the state. No nation ever benefited from a long war. Speed matters: a quick, imperfect action beats a perfect, slow one. Also: feed off the enemy - use existing resources instead of building everything from scratch.','Find one task you have been dragging for over a week. Today, finish a rough version of it in ONE 90-minute block. Imperfect and DONE. Report what happened.','What in my life is currently a "long war" draining my supplies? How do I shorten it?',0,NULL),
(1,3,'Ch.3 - Attack by Stratagem','Art of War, Chapter 3','Supreme excellence: subdue the enemy without fighting. Break resistance, not soldiers. The hierarchy: attack plans first, then alliances, then armies, cities last. And the immortal line: know the enemy and know yourself - a hundred battles, no danger.','Identify one recurring conflict or friction in your life (a person, a habit, an obstacle). Instead of fighting it head-on, design ONE move that makes the fight unnecessary (change the environment, the timing, or the approach). Execute or schedule it.','Did I win anything today without fighting? Did I fight anything I could have dissolved instead?',0,NULL),
(1,4,'Ch.4 - Tactical Dispositions','Art of War, Chapter 4','First make yourself invincible, THEN wait for the enemy''s vulnerability. Invincibility lies in defense (your systems, health, skills); opportunity lies in the enemy''s errors. The victorious warrior wins first and then goes to war; the defeated one goes to war first and then seeks to win.','List your 3 biggest personal vulnerabilities (e.g. phone addiction, sleep chaos, saying yes too fast). Pick ONE and install a structural defense against it today - not willpower, a SYSTEM.','Which vulnerability did the world try to exploit today? Did my defenses hold?',0,NULL),
(1,5,'Ch.5 - Energy','Art of War, Chapter 5','Direct methods (cheng) hold the line; indirect methods (chi) win. Combined they are inexhaustible like a circle. Great warriors seek momentum, not heroic individual effort - like rolling round stones down a mountain. Build systems whose ENERGY carries you.','Notice your energy peaks today. Do your hardest task exactly at your peak, easiest at your trough. Report whether riding momentum felt different from forcing effort.','Did I use momentum today, or brute force? Where is my round stone and where is my mountain?',0,NULL),
(1,6,'Ch.6 - Weak Points and Strong','Art of War, Chapter 6','Arrive first at the battlefield and you are fresh; arrive late and you fight exhausted. Attack where undefended; defend where attack is certain. Be formless - like water, adapt shape to terrain. Water wins by seeking the low, undefended path.','Do your hardest task FIRST tomorrow morning (arrive at the battlefield first). Also: find one "undefended" easy win you have been ignoring because it seemed too obvious. Take it.','Where did I arrive late (rushed, reactive) today? Where could I have arrived first?',0,NULL),
(1,7,'Ch.7 - Maneuvering','Art of War, Chapter 7','The hardest thing: turning the devious into the direct, misfortune into gain. Do not press a desperate foe; do not swallow bait. A whole army can be robbed of its spirit - a general of his presence of mind. Guard YOUR spirit: sharp in the morning, flagging by noon, spent by evening.','Protect your morning spirit tomorrow like a general guards supply lines: zero phone, zero news, zero other people''s demands until Deep Work 1 is done. Report the difference.','What robbed my spirit today - and did I hand it over voluntarily?',0,NULL),
(1,8,'Ch.8 - Variation in Tactics','Art of War, Chapter 8','The wise leader considers advantage AND disadvantage together. There are roads not to follow, towns not to besiege, commands not to obey. Five dangerous faults in a leader: recklessness, cowardice, hasty temper, delicacy of honor (touchy ego), over-solicitude (over-caring what others think).','Self-audit: rank the five faults from your strongest to weakest. For your #1 fault, write the exact situation that triggers it and one counter-move for next time it fires.','Which of the five faults fired today? Did I catch it in real time or only now?',0,NULL),
(1,9,'Ch.9 - The Army on the March','Art of War, Chapter 9','Read signs. Dust, birds, noise - everything reveals the enemy''s state. Applied to life: people and situations constantly leak information. Words humble but preparations increasing = advance coming. Words strong but ready to retreat = bluff. Observe behavior, not declarations.','People-watching drill: in one conversation or meeting today, ignore the WORDS and read only behavior (tone, posture, timing, what they avoid). Write down what the signs said vs what the words said.','What did someone''s behavior tell me today that their words did not?',0,NULL),
(1,10,'Ch.10 - Terrain','Art of War, Chapter 10','Six kinds of terrain, six kinds of self-inflicted defeat (flight, insubordination, collapse, ruin, disorganization, rout) - NONE caused by nature, ALL caused by the general. Know the terrain, know your troops. If you know neither, you lose every battle.','Map your personal terrain: write down your 3 most productive contexts (place+time+state) and your 3 most dangerous ones (where you always lose hours). Design tomorrow to live in the first and avoid the second.','Which terrain was I standing on when I lost time today? Did I choose that ground?',0,NULL),
(1,11,'Ch.11 - The Nine Situations','Art of War, Chapter 11','Ground changes everything - desperate ground makes soldiers fight hardest. Throw your troops where retreat is impossible and they prefer death to flight. Applied: commitment devices work. Burn selective boats. Also: unite your forces - a divided mind on dispersive ground loses.','Create ONE commitment device today for your most avoided task: tell someone the deadline, pay a stake, schedule a public checkpoint. Make retreat expensive.','Where do I keep an escape route open that guarantees I never fully commit?',0,NULL),
(1,12,'Ch.12 - Attack by Fire','Art of War, Chapter 12','Weapons of mass effect require timing and conditions - fire needs dry wind. Move only when there is true advantage; no leader should fight out of anger. Anger may turn to gladness, but a kingdom destroyed can never rise again. Emotional decisions are irreversible weapons fired at yourself.','24-hour rule installation: identify decisions you tend to make hot (messages sent angry, quitting impulses, spending). Write your personal "never decide hot" list and put it where you will see it.','Did any emotion try to fire my cannons today? Did I wait for the right wind?',0,NULL),
(1,13,'Ch.13 - The Use of Spies','Art of War, Chapter 13','Foreknowledge cannot come from spirits - only from people who know. Intelligence is the cheapest weapon: one insider''s knowledge saves years of war. Applied: mentors, books, people one step ahead of you ARE your spy network. Asking beats guessing.','Recruit one "spy" this week: message/ask one person who already achieved something you want (a grade, a skill, a habit) ONE specific question about how. Report their answer.','What did I struggle to figure out alone today that someone could have told me in 5 minutes?',0,NULL),
(1,14,'INTEGRATION EXAM - Sun Tzu','Review all 13 chapters + your maxim bank + all drill reports','Prove the principles live in your fingertips, not the page. Write from memory first, then check.','No drill - the exam IS the drill. Grade yourself brutally: fluff = fail.','After the exam: which chapter is weakest in me? (It becomes your review target.)',1,'["Name the Five Factors from Ch.1 and apply ALL five to your current biggest goal - specifically, not generically.","Ch.3: describe a real conflict from YOUR last month and design the without-fighting victory you should have used (or did use).","Ch.4: What does invincible first, victory second mean? What are your 3 structural defenses now installed?","Ch.6: Give one example from your own life this month of being water - adapting form to terrain.","Ch.8: Which of the five dangerous faults is yours? Cite the exact moment it last fired and your counter-move.","Ch.11: What commitment device did you build and what happened?","Ch.13: What did your spy tell you and how did it change your plan?","FINAL: In exactly 3 sentences, what is Sun Tzu''s system? (If you need 10 sentences, you have not compressed it - fail and retry.)"]');
